config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :user_detail, dependent: :destroy

  validates :name, presence: true , length: { in: 1..255 } 
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  mount_uploader :icon, ImageUploader

  belongs_to :user

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required 

  def new
    @user_form = UserForm.new
  end

  def create
    @user_form = UserForm.find_by_name_or_email(params[:session][:name_or_email])
    if @user_form.user && @user_form.user.authenticate(params[:session][:user][:password])
      session[:user_id] = @user_form.user.id
      redirect_to user_path(@user_form.user)
    else
      flash.now[:danger] = I18n.t("message.failed_login")
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = I18n.t("message.logout")
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
    @user_form = UserForm.new
  end

  def create
    @user_form = UserForm.initialize_for_params(params: params_user_form)
    if @user_form.save
      redirect_to user_path(@user_form.user.id)
    else
      render :new
    end
  end

  def edit
    @user_form = UserForm.find_by(current_user.id)
  end

  def update
    @user_form = UserForm.find_by(params_user_form[:user][:id])
    if @user_form.update(params: params_user_form)
      redirect_to user_path(@user_form.user.id)
    else
      render :edit
    end
  end

  def show
    @user_form = UserForm.find_by(params[:id])
  end

  def params_user_form
    params.require(:user_form).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end

  def current_user?(user_id)
    current_user.id == user_id
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def choose_method_new_or_edit
    if action_name == 'new'
      :post
    elsif action_name == 'edit'
      :patch
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OurTrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <nav class="navbar">
      <a class="navbar-brand" href="#">
        タイトル
      </a>
      <div class="collapse navbar-collapse" id="navbarEexample7">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="" role="button" aria-expanded="false">
              メニュー <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% if logged_in? %>
                <li role="presentation"><%= link_to "ユーザー",user_path(current_user) %></li>
                <li role="presentation"><%= link_to "ログアウト",session_path(current_user), method: :delete %></li>
              <% else %>
                <li role="presentation">"予定A"</li>
                <li role="presentation">"予定B"</li>
              <% end %>
            </ul>
          </li>
        </ul>
        <% if logged_in? %>
          <p class="navbar-text navbar-right">ようこそ <a href="#" class="navbar-link"><%= current_user.name %></a> さん。</p>
        <% else %>
          <p class="navbar-text navbar-right"><%= link_to "ログイン", new_session_path %></p>
        <% end %>
      </div>
    </nav>
  </header>
  <body>
    <% if flash.present? %>
      <div class="message_box">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value) %>
        <% end %>
      </div>
    <% end %>
    <%= yield %>
  </body>
  <footer>
    Copyright© missyu3 2020 
  </footer>
</html>

app/views/users/_form.html.erb
<% if @user_form.errors.present? && @user_form.errors.any? %>
  <div class="error_message_box">
    <ul>
      <% @user_form.errors.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-10">
      <div class='center_form'>
        <%= form_with(model: @user_form , url: users_path , method: choose_method_new_or_edit , local: true) do |form| %>
          <%= form.fields_for :user , @user_form.user do |user_fields| %>
            <div class="form-group">
              <%= user_fields.label :name , I18n.t("model.name")  %>
              <%= user_fields.text_field :name ,class:'form-control' %>
            </div>
          <% end %>
          <%= form.fields_for :user_detail , @user_form.user_detail  do |user_detail_fields| %>
            <div class="form-group">
              <%= user_detail_fields.label :email , I18n.t("model.email")  %>
              <%= user_detail_fields.email_field :email ,class:'form-control' %>
            </div>
            <div class="form-group">
              <%= user_detail_fields.label :icon , I18n.t("model.icon")  %>
              <%= user_detail_fields.file_field :icon %>
            </div>
          <% end %>
          <%= form.fields_for :user , @user_form.user  do |user_fields| %>
            <div class="form-group">
              <%= user_fields.label :password , I18n.t("model.password")  %>
              <%= user_fields.password_field :password ,class:'form-control' %>
            </div>
            <div class="form-group">
              <%= user_fields.label :password_digest , I18n.t("model.password_digest")  %>
              <%= user_fields.password_field :password_digest ,class:'form-control' %>
            </div>
          <% end %>
          <%= form.submit nil ,class:'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class='py-4 text-center'><%= I18n.t("title.user_edit") %></h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1 class='py-4 text-center'><%= I18n.t("title.user_new") %></h1>
<%= render 'form' %>

app/views/users/show.html.erb
<%= @user_form.user.name %>
<%= logged_in? %>
<%= link_to "編集", edit_user_path(@user_form.user.id) %>